version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8081:80"
    volumes:
      - ./backend:/var/www/html
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
